# cache GPG passphrase never expires until next reboot
default-cache-ttl 31536000
max-cache-ttl 31536000

# cache SSH passphrase never expires until next reboot
default-cache-ttl-ssh 31536000
max-cache-ttl-ssh 31536000

# SSH support
enable-ssh-support

# never cancel pinentry
pinentry-timeout 0

# Prevent GNOME Keyring / KWallet from intercepting
no-allow-external-cache

# Allow passphrase entry inline in terminal
allow-loopback-pinentry
