#!/usr/bin/env bash

# Define the path to the lock file
LOCK_FILE="/tmp/start-screen-recording-xorg.lock"
MONITOR=$1
PURPOSE=$2

# Check if the lock file already exists
if [ -e "$LOCK_FILE" ]; then
  echo "Script is already running."
  notify-send -r 27072 "screen recorder" "ERROR: script is already running"
  exit 1
fi

# Create the lock file
touch "$LOCK_FILE"

# Add a trap to delete the lock file on exit (even if the script fails)
trap "rm -f $LOCK_FILE" EXIT

gpu-screen-recorder \
    -w "$MONITOR" \
    -c matroska \
    -k hevc_10bit \
    -ac opus \
    -f 1 \
    -cursor yes \
    -restore-portal-session yes \
    -cr limited \
    -encoder gpu \
    -o "$HOME"/resource/videos/screencasts/"$PURPOSE"/screencast_$(date +%F_%H:%M:%S).mp4 \
    -q medium \
    -fm cfr \
    -a 'device:default_output|device:default_input' > /dev/null 2>&1 &

echo "RECORDING_SCREEN_BY_USER=1" >/tmp/is-screen-recording
