#!/usr/bin/env bash

# Define the path to the lock file
LOCK_FILE="/tmp/start-screen-recording-xorg.lock"
MONITOR=$1
PURPOSE=$2

# Check if the lock file already exists
if [ -e "$LOCK_FILE" ]; then
  echo "Script is already running."
  notify-send -r 27072 "screen recorder" "ERROR: script is already running"
  exit 1
fi

# Create the lock file
touch "$LOCK_FILE"

# Add a trap to delete the lock file on exit (even if the script fails)
trap "rm -f $LOCK_FILE" EXIT

appimage-run "$APPIMAGE_DIR"/Mechvibes-2.3.6-hotfix.AppImage --no-sandbox &
pkill -f dunst # prevent private things on screen casts
pkill -f periodic-random-wallpaper-switcher
mv ~/.zsh-history ~/.zsh-history.before-screen-recording # disable history commands during screencast

gpu-screen-recorder \
    -w "$MONITOR" \
    -c matroska \
    -k auto \
    -ac opus \
    -f 60 \
    -cursor yes \
    -restore-portal-session yes \
    -cr limited \
    -encoder gpu \
    -o "$HOME"/resource/videos/screencasts/"$PURPOSE"/screencast_$(date +%F_%H:%M:%S).mp4 \
    -q very_high \
    -a device:default_output|device:default_input > /dev/null 2>&1

screenkey &

echo "RECORDING_SCREEN_BY_USER=1" >/tmp/is-screen-recording
