backend = "glx";
vsync = true;
corner-radius = 10;
use-damage = true;
xrender-sync-fence = true;
unredir-if-possible = false;

# reduce stuttering
unredir-if-possible = true;

# detect-client-opacity = true;
# detect-rounded-corners = true;
# mark-wmwin-focused = true;
# mark-ovredir-focused = true;

# Blur
blur-method = "dual_kawase";
blur-strength = 10;
blur-background = true;

rules = (
  { match = "class_g = 'dwm' || window_type = 'dock'"; corner-radius = 0; opacity = 1; shadow = true;},
  { match = "class_g = 'dmenu'"; corner-radius = 0; opacity = 1; shadow = true; },
  { match = "class_g = 'qutebrowser'";      opacity = 1; blur-background = false; },
  # { match = "class_g = 'Conky'";          above = true; }, # prevent auto focus on this window when switching tags on dwm
  { match = "class_g = 'Dunst'";            shadow = true; }, # prevent auto focus on this window when switching tags on dwm

  # stuff with background blur
  # { match = "class_g = 'st-256color'";      blur-background = true; },
  # { match = "class_i = 'spterm'";           blur-background = true; },
  # { match = "class_g = 'Conky'";            above = false; blur-background = true; }, # prevent auto focus on this window when switching tags on dwm
  {
    animations = (
      {
        triggers = ["open", "show"];
        d = 0.2;
        scale-x = { duration = "d"; start = 0.9; end = 1; curve = "cubic-bezier(.63,0,.32,1.6)"; };
        scale-y = { duration = "d"; start = 0.9; end = 1; curve = "cubic-bezier(.63,0,.32,1.6)"; };
        offset-x = { duration = "d"; start = "window-width * 0.05"; end = 0; curve = "cubic-bezier(.63,0,.32,1.6)"; };
        offset-y = { duration = "d"; start = "window-height * 0.05"; end = 0; curve = "cubic-bezier(.63,0,.32,1.6)"; };
        opacity = { duration = "d"; start = 0; end = 1; curve = "cubic-bezier(.63,0,.32,1.6)"; };
      },
      {
        triggers = ["close", "hide"];
        d = 0.4;
        scale-x = { duration = "d"; start = 1; end = 0.9; curve = "cubic-bezier(0.85,0,0.15,1)"; };
        scale-y = { duration = "d"; start = 1; end = 0.9; curve = "cubic-bezier(0.85,0,0.15,1)"; };
        offset-x = { duration = "d"; end = "window-width * 0.05"; start = 0; curve = "cubic-bezier(0.85,0,0.15,1)"; };
        offset-y = { duration = "d"; end = "window-height * 0.05"; start = 0; curve = "cubic-bezier(0.85,0,0.15,1)"; };
        opacity = { duration = "d"; start = 1; end = 0; curve = "cubic-bezier(0.85,0,0.15,1)"; };
      },
      {
        triggers = ["geometry"];
        d = 0.35;
        saved-image-blend = 0;
        offset-x = { duration = "d"; start = "window-x-before - window-x"; end = 0; curve = "cubic-bezier(0.85,0,0.15,1)"; };
        offset-y = { duration = "d"; start = "window-y-before - window-y"; end = 0; curve = "cubic-bezier(0.85,0,0.15,1)"; };
        scale-x = { duration = "d"; start = "window-width-before / window-width"; end = 1; curve = "cubic-bezier(0.85,0,0.15,1)"; };
        scale-y = { duration = "d"; start = "window-height-before / window-height"; end = 1; curve = "cubic-bezier(0.85,0,0.15,1)"; };
      },
    );
  },
);

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

shadow = false;
shadow-radius = 15;
shadow-offset-x = -15;
shadow-offset-y = -15;
